version: '3.7'
networks:
  x_network:
    ipam:
      driver: default
services:
  x_mongo:
    container_name: "x_mongo"
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: x_data
    ports:
      - "27017:27017"
    networks:
      x_network:
    volumes:
      - ./initmongo.js:/docker-entrypoint-initdb.d/initmongno.js
  x_api:
    container_name: "x_api"
    build: ./
    ports:
      - "9090:9090"
    environment:
      - MONGODB_DATABASE=x_data
      - MONGODB_HOST=x_mongo
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
      #set custom environment variables from X-Server App Dockerfile here
    networks:
      x_network:
    depends_on:
      - x_mongo