FROM openjdk:8u222
ENV X_PROFILE prod
ENV SERVER_PORT 9090
ENV MONGODB_DATABASE x_data
ENV MONGODB_HOST localhost
ENV MONGODB_PORT 27017
ENV MONGODB_USERNAME admin
ENV MONGODB_PASSWORD password
ENV MONGODB_AUTHENTICATION_DATABASE admin
ENV OAUTH_CLIENT_ID client_id
ENV OAUTH_CLIENT_SECRET password
ENV OAUTH_SIGNING_KEY key
ENV OAUTH_TOKEN_EXPIRED_TIME 200
ENV OAUTH_REFRESH_TOKEN_EXPIRED_TIME 220
ENV DEFAULT_ADMIN_USERNAME admin
ENV DEFAULT_ADMIN_PASSWORD adminadmin
ENV DEFAULT_ADMIN_EMAIL admin@admin.com
ENV LOG_FILE_NAME logs.log
ENV LOG_FILE_MAX_SIZE 10MB
VOLUME /tmp
COPY build/libs/* x_app.jar
EXPOSE $SERVER_PORT
ENTRYPOINT ["java", "-jar", "x_app.jar"]